version: 2

jobs:

  build:
    working_directory: ~/oauth2_proxy

    docker:
      - image: factominc/elixir_python

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.0-ce

      # Build the containers
      - run:
          name: Build the baseline images
          command: |
            docker build -t oauth2_proxy .

      - run:
          name: Push images to DockerHub
          command: |

           # Login to DockerHub
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            
            # If there is a tag, use it
            if [ "$CIRCLE_TAG" != "" ]; then
              docker tag oauth2_proxy factominc/oauth2_proxy:${CIRCLE_TAG}
              docker push factominc/oauth2_proxy:${CIRCLE_TAG}
            fi
            
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              # Tag master as latest
              docker tag oauth2_proxy factominc/oauth2_proxy:latest
              docker push factominc/oauth2_proxy:latest
            fi

            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            
              # Tag develop as develop anyhow
              docker tag oauth2_proxy factominc/oauth2_proxy:develop
              docker push factominc/oauth2_proxy:develop
            fi

            docker logout

      - run:
          name: Push images to AWS ECR
          command: |
            # Login to AWS ECR
            login="$(aws ecr get-login  --no-include-email --region $AWS_REGION)"
            ${login}
            
            # If there is a tag, use it
            if [ "$CIRCLE_TAG" != "" ]; then
              docker tag oauth2_proxy ${AWS_REPO_BASE_URI}/oauth2_proxy:${CIRCLE_TAG}
              docker push ${AWS_REPO_BASE_URI}/oauth2_proxy:${CIRCLE_TAG}
            fi
            
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              # Tag master as latest
              docker tag oauth2_proxy ${AWS_REPO_BASE_URI}/oauth2_proxy:latest
              docker push ${AWS_REPO_BASE_URI}/oauth2_proxy:latest
            fi

            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            
              # Tag develop as develop anyhow
              docker tag oauth2_proxy ${AWS_REPO_BASE_URI}/oauth2_proxy:develop
              docker push ${AWS_REPO_BASE_URI}/oauth2_proxy:develop
            fi

            docker logout

# The flow is
#    build
#      |
#      ---------- test
#                   |
#                   ---------- coveralls
#                   |
#                   ---------- docker_build
#
#

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/

  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: develop
    jobs:
      - build:
          context: org-global
